-- 테이블 생성
CREATE TABLE TB_STUDENT(
	STD_NO NUMBER PRIMARY KEY,
	STD_NAME VARCHAR2(20) NOT NULL,
	STD_AGE NUMBER NOT NULL,
	STD_GENDER CHAR(1) CHECK (STD_GENDER IN ('M', 'F')),
	STD_SCORE CHAR(1) CHECK (STD_SCORE IN ('A', 'B', 'C', 'D', 'F'))
);



COMMENT ON COLUMN TB_STUDENT.STD_NO IS '학생 번호';
COMMENT ON COLUMN TB_STUDENT.STD_NAME IS '학생 이름';
COMMENT ON COLUMN TB_STUDENT.STD_AGE IS '학생 나이';
COMMENT ON COLUMN TB_STUDENT.STD_GENDER IS '학생 성별';
COMMENT ON COLUMN TB_STUDENT.STD_SCORE IS '학생 성적';


-- 시퀀스 생성
CREATE SEQUENCE SEQ_TODO_NO NOCACHE;

-- 샘플 데이터

-- 예시 데이터 삽입
INSERT INTO TB_STUDENT (STD_NO, STD_NAME, STD_AGE, STD_GENDER, STD_SCORE)
VALUES (1, '나찬웅', 27, 'M', 'A');

INSERT INTO TB_STUDENT (STD_NO, STD_NAME, STD_AGE, STD_GENDER, STD_SCORE)
VALUES (2, '유근창', 32, 'F', 'B');

INSERT INTO TB_STUDENT (STD_NO, STD_NAME, STD_AGE, STD_GENDER, STD_SCORE)
VALUES (3, '신휘호', 29, 'M', 'C');

INSERT INTO TB_STUDENT (STD_NO, STD_NAME, STD_AGE, STD_GENDER, STD_SCORE)
VALUES (4, '박준형', 24, 'F', 'F');


COMMIT;